// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-usability/AccessibilityReadability.tsx": () => import("../components/mockups/home-usability/AccessibilityReadability.tsx"),
  "./components/mockups/home-usability/HierarchyClarity.tsx": () => import("../components/mockups/home-usability/HierarchyClarity.tsx"),
  "./components/mockups/home-usability/InteractionAffordance.tsx": () => import("../components/mockups/home-usability/InteractionAffordance.tsx")
};
