export const FALLBACK_NAMES = [
	{
		id: "1",
		name: "Whiskers",
		description: "Classic tabby cat with a championship stare.",
		pronunciation: "WHIS-kerz",
		avgRating: 1650,
		isActive: true,
		isHidden: false,
		status: "candidate",
	},
	{
		id: "2",
		name: "Shadow",
		description: "A sleek midnight prowler with mysterious energy.",
		pronunciation: "SHAD-oh",
		avgRating: 1615,
		isActive: true,
		isHidden: false,
		status: "candidate",
	},
	{
		id: "3",
		name: "Luna",
		description: "Soft, bright, and elegant like moonlight on a windowsill.",
		pronunciation: "LOO-nah",
		avgRating: 1590,
		isActive: true,
		isHidden: false,
		status: "candidate",
	},
	{
		id: "4",
		name: "Muffin",
		description: "Cozy, sweet, and impossible not to love.",
		pronunciation: "MUF-in",
		avgRating: 1560,
		isActive: true,
		isHidden: false,
		status: "candidate",
	},
	{
		id: "5",
		name: "Mittens",
		description: "Playful charm with tiny-sock energy.",
		pronunciation: "MIT-enz",
		avgRating: 1535,
		isActive: true,
		isHidden: false,
		status: "candidate",
	},
	{
		id: "6",
		name: "Pepper",
		description: "A sharp little name for a cat with attitude.",
		pronunciation: "PEP-er",
		avgRating: 1510,
		isActive: true,
		isHidden: false,
		status: "candidate",
	},
	{
		id: "7",
		name: "Biscuit",
		description: "Warm, fluffy, and suspiciously good at naps.",
		pronunciation: "BIS-kit",
		avgRating: 1495,
		isActive: true,
		isHidden: false,
		status: "candidate",
	},
	{
		id: "8",
		name: "Ziggy",
		description: "Bright, weird, and built for a dramatic entrance.",
		pronunciation: "ZIG-ee",
		avgRating: 1475,
		isActive: true,
		isHidden: false,
		status: "candidate",
	},
] as const;

export function getFallbackNames(includeHidden = true) {
	return FALLBACK_NAMES.filter((item) => includeHidden || !item.isHidden).map((item) => ({
		...item,
	}));
}
